---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: odf4registry
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem

